import Emittery from "emittery";

export const EventEmitter = new Emittery();

export const EVENT_NAMES = {
  SEND_MESSAGE: "SEND_MESSAGE",
  MESSAGE_COMPLETE: "MESSAGE_COMPLETE",
  AI_AUTO_RENAME: "AI_AUTO_RENAME",
  CLEAR_MESSAGES: "CLEAR_MESSAGES",
  ADD_ASSISTANT: "ADD_ASSISTANT",
  EDIT_MESSAGE: "EDIT_MESSAGE",
  REGENERATE_MESSAGE: "REGENERATE_MESSAGE",
  CHAT_COMPLETION_PAUSED: "CHAT_COMPLETION_PAUSED",
  ESTIMATED_TOKEN_COUNT: "ESTIMATED_TOKEN_COUNT",
  SHOW_ASSISTANTS: "SHOW_ASSISTANTS",
  SHOW_CHAT_SETTINGS: "SHOW_CHAT_SETTINGS",
  SHOW_SESSION_SIDEBAR: "SHOW_SESSION_SIDEBAR",
  SWITCH_SESSION_SIDEBAR: "SWITCH_SESSION_SIDEBAR",
  SWITCH_ASSISTANT: "SWITCH_ASSISTANT",
  NEW_CONTEXT: "NEW_CONTEXT",
  NEW_BRANCH: "NEW_BRANCH",
  COPY_SESSION_IMAGE: "COPY_SESSION_IMAGE",
  EXPORT_SESSION_IMAGE: "EXPORT_SESSION_IMAGE",
  LOCATE_MESSAGE: "LOCATE_MESSAGE",
  ADD_NEW_SESSION: "ADD_NEW_SESSION",
  RESEND_MESSAGE: "RESEND_MESSAGE",
  SHOW_MODEL_SELECTOR: "SHOW_MODEL_SELECTOR",
  QUOTE_TEXT: "QUOTE_TEXT",
  EDIT_CODE_BLOCK: "EDIT_CODE_BLOCK",
  CHANGE_SESSION: "CHANGE_SESSION",
  COPY_CODE_SUCCESS: "COPY_CODE_SUCCESS",
  SESSION_UPDATED: "SESSION_UPDATED",
  MESSAGE_BLOCK_UPDATED: "MESSAGE_BLOCK_UPDATED",
};
